package com.itheima.pojo;

import com.itheima.util.DateUtil;
import org.springframework.format.annotation.DateTimeFormat;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.ID
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCTNUM
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private String productNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCTNAME
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CITYNAME
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.DEPARTURETIME
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm")
    private Date departureTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCTPRICE
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private BigDecimal productPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCTDESC
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRODUCTSTATUS
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    private Integer productStatus;

    private String departureTimeStr;

    public String getDepartureTimeStr() {
        if (departureTime != null){
            String time = DateUtil.getStringTime(departureTime);
            departureTimeStr = time;
        }
        return departureTimeStr;
    }

    public void setDepartureTimeStr(String departureTimeStr) {
        this.departureTimeStr = departureTimeStr;
    }

    public String getProductStatusStr() {
        if (productStatus != null){
            if (productStatus==1){
                productStatusStr = "开启";
            }else if (productStatus==0){
                productStatusStr = "关闭";
            }
        }
        return productStatusStr;
    }

    public void setProductStatusStr(String productStatusStr) {
        this.productStatusStr = productStatusStr;
    }

    private String productStatusStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.ID
     *
     * @return the value of PRODUCT.ID
     *
     * @mbggenerated Tue Sep 25 19:18:43 CST 2018
     */
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getProductNum() {
        return productNum;
    }

    public void setProductNum(String productNum) {
        this.productNum = productNum;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Date getDepartureTime() {
        return departureTime;
    }

    public void setDepartureTime(Date departureTime) {
        this.departureTime = departureTime;
    }

    public BigDecimal getProductPrice() {
        return productPrice;
    }

    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }

    public String getProductDesc() {
        return productDesc;
    }

    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    public Integer getProductStatus() {
        return productStatus;
    }

    public void setProductStatus(Integer productStatus) {
        this.productStatus = productStatus;
    }

    @Override
    public String toString() {
        return "Product{" +
                "id='" + id + '\'' +
                ", productNum='" + productNum + '\'' +
                ", productName='" + productName + '\'' +
                ", cityName='" + cityName + '\'' +
                ", departureTime=" + departureTime +
                ", productPrice=" + productPrice +
                ", productDesc='" + productDesc + '\'' +
                ", productStatus=" + productStatus +
                ", departureTimeStr='" + departureTimeStr + '\'' +
                ", productStatusStr='" + productStatusStr + '\'' +
                '}';
    }
}